name: Upload SARIF
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  sarif:
    name: upload sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
        with:
          version: '1.7'
          force: 'false'
      
      - name: Get findings
        shell: bash    
        env:
           JIT_API_CLIENT_ID: ${{ secrets.JIT_API_CLIENT_ID }}
           JIT_API_CLIENT_SECRET: ${{ secrets.JIT_API_CLIENT_SECRET }}
        run: |
          export JIT_ACCESS_TOKEN=$(curl -X POST -d "{\"clientId\":\"$JIT_API_CLIENT_ID\", \"secret\":\"$JIT_API_CLIENT_SECRET\"}" -H "Content-Type: application/json" https://api.cto.jitdev.io/authentication/login | jq -r .accessToken)
          echo $JIT_ACCESS_TOKEN
          curl -H "Authorization: Bearer $JIT_ACCESS_TOKEN" -H "Accept: application/sarif+json" https://api.cto.jitdev.io/findings/ | jq '.findings' > /tmp/findings.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: /tmp/findings.sarif
